name: tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "*"

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: hoxbro/actions/pre-commit@main

  unit_test_suite:
    name: unit:py-${{ matrix.python-version }}:${{ matrix.os }}
    needs: [pre-commit]
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.10", "3.11", "3.12", "3.13", "3.14"]
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v6
        with:
          python-version: ${{ matrix.python-version }}
      - name: Get cache directory and version
        id: cache-info
        shell: bash
        run: |
          output=$(uv run param-lsp --cache-dir)
          echo "dir=${output%%::*}" >> $GITHUB_OUTPUT
          echo "version=${output##*::}" >> $GITHUB_OUTPUT
      - name: Restore param-lsp cache
        id: cache-restore
        uses: actions/cache/restore@v4
        with:
          path: ${{ steps.cache-info.outputs.dir }}
          key: ${{ runner.os }}-param-lsp-${{ steps.cache-info.outputs.version }}-${{ hashFiles('**/pyproject.toml') }}
          restore-keys: |
            ${{ runner.os }}-param-lsp-${{ steps.cache-info.outputs.version }}-
      - name: Generate cache
        if: steps.cache-restore.outputs.cache-hit != 'true'
        run: uv run param-lsp --generate-cache
      - name: Testing
        run: uv run -m pytest tests/
      - name: Save param-lsp cache
        if: always()
        uses: actions/cache/save@v4
        with:
          path: ${{ steps.cache-info.outputs.dir }}
          key: ${{ steps.cache-restore.outputs.cache-primary-key }}

  result_test_suite:
    name: result:test
    needs: [unit_test_suite]
    if: always()
    runs-on: ubuntu-latest
    steps:
      - name: check for failures
        if: contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled')
        run: echo job failed && exit 1
